{% set name = "kennard-stone" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: d1ca284aa67734882738e2b8c10266362065a3ec70b2bcf63be1e96e21d4246b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python>=3.7
    - pip
  run:
    - python>=3.7
    - numpy
    - scikit-learn

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu9824/kennard_stone
  summary: A method for selecting samples by spreading the training data evenly.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
